apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: user-config-secrets
  namespace: jenkins
stringData:
  EXECUTORS_AMOUNT: "6"
  SYSTEM_MESSAGE: "Wellcome to Jenkins!"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-user-configuration
data:
  1-configure-executors.groovy: |
    import jenkins.*
    import jenkins.model.*
    import hudson.*
    import hudson.model.*
    Jenkins jenkins = Jenkins.getInstance()
    jenkins.setNumExecutors(Integer.valueOf(secrets["EXECUTORS_AMOUNT"]))
    jenkins.save()
  2-configure-theme.groovy: | 
    import jenkins.*
    import jenkins.model.*
    import hudson.*
    import hudson.model.*
    import org.jenkinsci.plugins.simpletheme.ThemeElement
    import org.jenkinsci.plugins.simpletheme.CssTextThemeElement
    import org.jenkinsci.plugins.simpletheme.CssUrlThemeElement

    Jenkins jenkins = Jenkins.getInstance()

    def decorator = Jenkins.instance.getDescriptorByType(org.codefirst.SimpleThemeDecorator.class)

    List<ThemeElement> configElements = new ArrayList<>();
    configElements.add(new CssTextThemeElement("DEFAULT"));
    configElements.add(new CssUrlThemeElement("https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-light-green.css"));
    decorator.setElements(configElements);
    decorator.save();

    jenkins.save()
  3-system-message.yaml: |
    jenkins:
      systemMessage: ${SYSTEM_MESSAGE}
  4-system-message.yaml: |
    jenkins:
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: ${user1-name}
              password: ${user1-pass}
            - id: ${user2-name}
              password: ${user2-pass}