apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: synergy
  namespace: jenkins-prod
spec:
  notifications:
  - level: info
    verbose: true
    name: slack
    slack:
      webHookURLSecretKeySelector:
        secret:
          name: jenkins-synergy-slack-notification
        key: url
  configurationAsCode:
    configurations: 
    - name: jenkins-synergy-configurations
    secret:
      name: "jenkins-eosc-synergy-oauth-secrets"
  groovyScripts:
    configurations:
      - name: jenkins-synergy-configurations
    secret:
      name: "jenkins-eosc-synergy-oauth-secrets"
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    # - name: kubernetes
    #   version: "1.30.6"
    # - name: workflow-job
    #   version: "2.42"
    # - name: workflow-aggregator
    #   version: "2.6"
    # - name: git
    #   version: "4.10.0"
    # - name: job-dsl
    #   version: "1.78"
    # - name: configuration-as-code
    #   version: "1.54"
    # - name: kubernetes-credentials-provider
    #   version: "0.20"
    # - name: github-oauth
    #   version: "0.34"
    # - name: matrix-auth
    #   version: "2.6.8"
    # - name: slack
    #   version: "2.48"
    # - name: blueocean
    #   version: "1.25.1"
    # - name: docker-plugin
    #   version: "1.2.3"
    # - name: docker-workflow
    #   version: "1.26"
    # - name: workflow-cps-global-lib
    #   version: "2.21"
    # - name: pipeline-github-lib
    #   version: "1.0"
    # - name: authorize-project
    #   version: "1.4.0"
    # - name: oauth-credentials
    #   version: "0.4"
    # - name: generic-webhook-trigger
    #   version: "1.77"
    # - name: gitlab-branch-source
    #   version: "1.5.9"
    # - name: cmakebuilder
    #   version: "4.1.0"





    - name: kubernetes
      version: "1.31.3"
    - name: workflow-job
      version: "2.42"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.10.3"
    - name: job-dsl
      version: "1.78.3"
    - name: configuration-as-code
      version: "1.55.1"
    - name: kubernetes-credentials-provider
      version: "0.20"
    - name: authentication-tokens
      version: "1.4"
    - name: credentials
      version: "2.6.2"
    - name: credentials-binding
      version: "1.27.1"
    - name: ssh-credentials
      version: "1.19"
    - name: plain-credentials
      version: "1.8"
    - name: kubernetes-credentials
      version: "0.9.0"
    - name: pipeline-stage-view
      version: "2.21"
    - name: pipeline-rest-api
      version: "2.21"
    - name: workflow-cps-global-lib
      version: "2.21"
    - name: git-client
      version: "3.11.0"
    - name: pipeline-input-step
      version: "2.12"
    - name: pipeline-model-definition
      version: "1.9.3"
    - name: pipeline-model-extensions
      version: "1.9.3"
    - name: jsch
      version: "0.1.55.2"
    - name: git-server
      version: "1.10"
    - name: pipeline-graph-analysis
      version: "1.12"


    - name: matrix-auth
      version: "3.0.1"
    - name: slack
      version: "2.49"
    - name: blueocean
      version: "1.25.2"
    - name: docker-plugin
      version: "1.2.6"
    - name: docker-workflow
      version: "1.27"
    - name: pipeline-github-lib
      version: "1.0"
    - name: github-oauth
      version: "0.37"
    - name: authorize-project
      version: "1.4.0"
    - name: oauth-credentials
      version: "0.5"
    - name: generic-webhook-trigger
      version: "1.83"
    - name: gitlab-branch-source
      version: "1.5.9"
    - name: build-timeout
      version: "1.20"
    - name: dashboard-view
      version: "2.17"
    - name: docker-compose-build-step
      version: "1.0"
    - name: email-ext
      version: "2.83"
    - name: embeddable-build-status
      version: "2.0.3"
    - name: git-parameter
      version: "0.9.13"
    - name: gradle
      version: "1.37.1"
    - name: hashicorp-vault-pipeline
      version: "1.3"
    - name: jquery-detached
      version: "1.2.1"
    - name: jaxb
      version: "2.3.0.1"
    - name: ldap
      version: "2.7"
    - name: openstack-cloud
      version: "2.60"
    - name: pipeline-utility-steps
      version: "2.10.0"
    - name: rebuild
      version: "1.32"
    - name: selenium-builder
      version: "1.14"
    - name: seleniumhtmlreport
      version: "1.1"
    - name: ssh-agent
      version: "1.23"
    - name: subversion
      version: "2.15.1"
    - name: throttle-concurrents
      version: "2.4"
    - name: timestamper
      version: "1.13"
    - name: variant
      version: "1.4"
    - name: warnings-ng
      version: "9.5.1"
    - name: ws-cleanup
      version: "0.39"
    - name: cmakebuilder
      version: "4.1.0"
    plugins:
    - name: simple-theme-plugin
      version: "0.7"
    disableCSRFProtection: false  
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.319.1-lts-alpine
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 100
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 10
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    - name: backup-synergy # container responsible for the backup and restore
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "3" # keep only the 2 most recent backups
      image: virtuslab/jenkins-operator-backup-pvc:v0.1.0 # look at backup/pvc directory
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /jenkins-home # Jenkins home volume
        name: jenkins-home
      - mountPath: /backup # backup volume
        name: backup
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: backup-pvc-jenkins-synergy
  backup:
    containerName: backup-synergy # container name is responsible for backup
    action:
      exec:
        command:
        - /home/user/bin/backup.sh # this command is invoked on "backup" container to make backup, for example /home/user/bin/backup.sh <backup_number>, <backup_number> is passed by operator
    interval: 30 # how often make backup in seconds
    makeBackupBeforePodDeletion: true # make a backup before pod deletion
  restore:
    containerName: backup-synergy # container name is responsible for restore backup
    action:
      exec:
        command:
        - /home/user/bin/restore.sh # this command is invoked on "backup" container to make restore backup, for example /home/user/bin/restore.sh <backup_number>, <backup_number> is passed by operator
    getLatestAction:
      exec:
        command:
        - /home/user/bin/get-latest.sh # this command is invoked on "backup" container to get last backup number before pod deletion. If you don't omit it in CR, you can lose data
  seedJobs:
  - id: jenkins-operator
    targets: "jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: main
    repositoryUrl: https://github.com/lip-casc/jenkins-seed-jobs






    