apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: synergy
  namespace: jenkins-prod
spec:
  notifications:
  - level: info
    verbose: true
    name: slack
    slack:
      webHookURLSecretKeySelector:
        secret:
          name: jenkins-synergy-slack-notification
        key: url
  configurationAsCode:
    configurations: 
    - name: jenkins-synergy-configurations
    secret:
      name: "jenkins-eosc-synergy-oauth-secrets"
  groovyScripts:
    configurations:
      - name: jenkins-synergy-configurations
    secret:
      name: "jenkins-eosc-synergy-oauth-secrets"
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    plugins:
    - name: simple-theme-plugin
      version: "103.va_161d09c38c7"
    - name: slack
      version: "608.v19e3b_44b_b_9ff"
    - name: blueocean
      version: "1.25.3"
    - name: docker-plugin
      version: "1.2.8"
    - name: docker-workflow
      version: "1.28"
    - name: github-oauth
      version: "0.37"
    - name: pipeline-github-lib
      version: "36.v4c01db_ca_ed16"
    - name: authorize-project
      version: "1.4.0"
    - name: oauth-credentials
      version: "0.5"
    - name: generic-webhook-trigger
      version: "1.84"
    - name: gitlab-branch-source
      version: "625.v85cf3a_400cfe"
    - name: build-timeout
      version: "1.20"
    - name: dashboard-view
      version: "2.432.va_712ce35862d"
    - name: docker-compose-build-step
      version: "1.0"
    - name: email-ext
      version: "2.87"
    - name: embeddable-build-status
      version: "2.0.3"
    - name: git-parameter
      version: "0.9.16"
    - name: gradle
      version: "1.38"
    - name: hashicorp-vault-pipeline
      version: "1.3"
    - name: jquery-detached
      version: "1.2.1"
    - name: jaxb
      version: "2.3.0.1"
    - name: ldap
      version: "2.9"
    - name: openstack-cloud
      version: "2.61"
    - name: pipeline-utility-steps
      version: "2.12.0"
    - name: rebuild
      version: "1.33.1"
    - name: selenium-builder
      version: "1.14"
    - name: seleniumhtmlreport
      version: "1.1"
    - name: ssh-agent
      version: "1.24.1"
    - name: subversion
      version: "2.15.4"
    - name: throttle-concurrents
      version: "2.8"
    - name: timestamper
      version: "1.17"
    - name: variant
      version: "1.4"
    - name: warnings-ng
      version: "9.11.1"
    - name: ws-cleanup
      version: "0.42"
    - name: cmakebuilder
      version: "4.1.1"
    - name: prism-api
      version: "1.26.0-2"
    disableCSRFProtection: false  
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.319.2-lts-alpine
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 600
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 10
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 580
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    - name: backup-synergy # container responsible for the backup and restore
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "3" # keep only the 2 most recent backups
      image: virtuslab/jenkins-operator-backup-pvc:v0.1.1 # look at backup/pvc directory
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /jenkins-home # Jenkins home volume
        name: jenkins-home
      - mountPath: /backup # backup volume
        name: backup
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: backup-pvc-jenkins-synergy
  backup:
    containerName: backup-synergy # container name is responsible for backup
    action:
      exec:
        command:
        - /home/user/bin/backup.sh # this command is invoked on "backup" container to make backup, for example /home/user/bin/backup.sh <backup_number>, <backup_number> is passed by operator
    interval: 30 # how often make backup in seconds
    makeBackupBeforePodDeletion: true # make a backup before pod deletion
  restore:
    containerName: backup-synergy # container name is responsible for restore backup
    action:
      exec:
        command:
        - /home/user/bin/restore.sh # this command is invoked on "backup" container to make restore backup, for example /home/user/bin/restore.sh <backup_number>, <backup_number> is passed by operator
    getLatestAction:
      exec:
        command:
        - /home/user/bin/get-latest.sh # this command is invoked on "backup" container to get last backup number before pod deletion. If you don't omit it in CR, you can lose data
  seedJobs:
  - id: jenkins-operator
    targets: "jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: main
    repositoryUrl: https://github.com/lip-casc/jenkins-seed-jobs
   
