apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc-jenkins-synergy
  namespace: jenkins-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi